### ISSUE TITLE
当gost二进制程序和ui在同一个网络环境中，ui无法通过本地连接到后端

### ISSUE THREAD

**Issue by sky22333** [cnwhy/gost-ui#3]
例如我构建了一个镜像同时运行UI和后端
```
FROM caddy:alpine

COPY --from=gogost/gost /bin/gost /app/gost
COPY --from=gogost/gost-ui /usr/share/nginx/html/ /srv

COPY gost.yml /app/
COPY Caddyfile /etc/caddy/

WORKDIR /app

# 设置容器启动时同时运行Caddy和gost
CMD ["sh", "-c", "caddy run --config /etc/caddy/Caddyfile & /app/gost -C /app/gost.yml && wait"]
```

`gost.yml`配置
```
api:
  addr: :18080
  pathPrefix: /api
  accesslog: true
  auth:
    username: 123123
    password: 123123
  auther: auther-0
```
此时我的面板无法通过本地IP连接后端，将本地IP改为公网IP能正常访问，希望能支持直接通过本地IP访问后端。另外面板中编辑配置的输入框内貌似不支持滚动，当配置太长时，只能通过改变输入框大小才能看到下面的配置。

![Image](https://github.com/user-attachments/assets/6f2e1ce4-f728-421b-a040-83a9c647ff38)
